INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (99, 123.45, 'Antonio');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (100,1.0, 'Adnan');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (101, 150.0, 'Ali');
